### ISSUE TITLE
Pod install does not work unless you remove the , '2.3.79' from the podfile

### ISSUE THREAD

**Issue by akac** [tomtom-international/maps-sdk-for-ios-examples#1]
Installing the pods fails unless you remove the 
, '2.3.79'
version from each pod line.

**Comment by 7tomek** [comment]
Hi, Alex. Which version of Cocoapods do you use? Can you send the type of message which you got on a terminal?
Did you try to use cmd 'pod install --repo-update'?

**Comment by akac** [comment]
Yes, I did do a repo-update, but the latest that COCOAPODS: 1.5.3 could find for me was:
PODS:
  - TomTomOnlineSDKMaps (2.3.6):
    - TomTomOnlineUtils (= 2.3.6)
  - TomTomOnlineSDKMapsStaticImage (2.3.6):
    - TomTomOnlineUtils (= 2.3.6)
  - TomTomOnlineSDKMapsUIExtensions (2.3.6):
    - TomTomOnlineSDKMaps (= 2.3.6)
  - TomTomOnlineSDKRouting (2.3.6):
    - TomTomOnlineUtils (= 2.3.6)
  - TomTomOnlineSDKSearch (2.3.6):
    - TomTomOnlineUtils (= 2.3.6)
  - TomTomOnlineSDKTraffic (2.3.6):
    - TomTomOnlineUtils (= 2.3.6)
  - TomTomOnlineUtils (2.3.6)

**Comment by akac** [comment]
Of course with the 2.3.6 version of the SDK, the Sample app doesn't work either.

**Comment by 7tomek** [comment]
Ok I think this is problem with cocoapods repo
`pod repo remove master`
and next `pod setup` or `pod install`

**Comment by akac** [comment]
Took an hour or so, but that seemed to work:
`Installing TomTomOnlineSDKMaps 2.3.79 (was 2.3.6 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
`
