### ISSUE TITLE
Does not support XCode 10's default new build system

### ISSUE THREAD

**Issue by akac** [tomtom-international/maps-sdk-for-ios-examples#2]
Got the latest code, grabbed the latest pods, added my keys to the info.plist and set my bundleID, Xcode 10 (latest) and build and you will get these errors. If you change to the old build system, it will work fine.

Since Xcode 10 is the latest development toolchain - it would be good to support the new build system.

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon21ManeuverIconGenerator", referenced from:
      objc-class-ref in TableBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon11TrafficCell", referenced from:
      objc-class-ref in TableBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon12ManeuverCell", referenced from:
      objc-class-ref in TableBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon7ETAView", referenced from:
      objc-class-ref in RoutingBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon7TTColor", referenced from:
      objc-class-ref in BaseViewController.o
      objc-class-ref in SearchBaseViewController.o
      objc-class-ref in CollectionBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon8Progress", referenced from:
      objc-class-ref in BaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon11FormatUtils", referenced from:
      objc-class-ref in TableBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon5Toast", referenced from:
      objc-class-ref in BaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon15LocationManager", referenced from:
      objc-class-ref in SearchBaseViewController.o
      objc-class-ref in TableBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon12TTCoordinate", referenced from:
      objc-class-ref in RoutingBaseViewController.o
      objc-class-ref in MapBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon11OptionsView", referenced from:
      objc-class-ref in ButtonsBaseViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

or if building for device:
`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon21ManeuverIconGenerator", referenced from:
      objc-class-ref in TableBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon11TrafficCell", referenced from:
      objc-class-ref in TableBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon12ManeuverCell", referenced from:
      objc-class-ref in TableBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon7ETAView", referenced from:
      objc-class-ref in RoutingBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon7TTColor", referenced from:
      objc-class-ref in BaseViewController.o
      objc-class-ref in SearchBaseViewController.o
      objc-class-ref in CollectionBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon8Progress", referenced from:
      objc-class-ref in BaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon11FormatUtils", referenced from:
      objc-class-ref in TableBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon5Toast", referenced from:
      objc-class-ref in BaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon15LocationManager", referenced from:
      objc-class-ref in SearchBaseViewController.o
      objc-class-ref in TableBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon12TTCoordinate", referenced from:
      objc-class-ref in RoutingBaseViewController.o
      objc-class-ref in MapBaseViewController.o
  "_OBJC_CLASS_$__TtC21MapsSDKExamplesCommon11OptionsView", referenced from:
      objc-class-ref in ButtonsBaseViewController.o
ld: symbol(s) not found for architecture arm64`

**Comment by 7tomek** [comment]
We are working to resolve the issue. Let you know.

**Comment by 7tomek** [comment]
Fixed Bug 2.3.98 release
